# Generated by Django 4.2.3 on 2024-09-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addrrecode',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['create_time', '-description']},
        ),
        migrations.AddField(
            model_name='addrrecode',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='views'),
        ),
        migrations.AlterUniqueTogether(
            name='addrrecode',
            unique_together={('description', 'addr')},
        ),
    ]
